@startuml
'https://plantuml.com/sequence-diagram

title POST /prior/api/v1/inventory/inventory/{id}

actor User as u
entity API as a
database Database as d

u->a : POST /prior/api/v1/inventory/inventory/{id}
a->d : Find character by id
a->a : Validate character

alt Character found
    d-->a : Character data
    a->d : Find monster by id
    a->a : Validate monster

    alt Monster found
        d-->a : Monster data
        a->d : Find inventory by id
        a->a : Validate inventory

        alt Inventory found
            a->a : Validate equals item

            alt Item name exists
                d-->a : Default inventory data
                a->d : Insert into inventory
                d-->a : New inventory data
                a->u : 200 OK
                a->u : "Successfully updated data"
                a->u : JSON Inventory data
                else Item name is unique
                a->u : 400 Bad Request
                a->u : "Item not found"
            end

        else Inventory not found
            a->u : 400 Bad Request
            a->u : "Inventory not found"
        end

    else Monster not found
        a->u : 400 Bad Request
        a->u : "Monster not found"
    end

else Character not found
    a->u : 400 Bad Request
    a->u : "Character not found"
end

@enduml