@startuml
'https://plantuml.com/sequence-diagram

title GET /prior/api/v1/account

actor User as u
entity API as a
database Database as d

u->a : GET /prior/api/v1/account
a->d: Find all accounts
d-->a : Account data
a->a : Validate accounts

alt Account found
    a->u : 200 OK
    a->u : "Data retrieved successfully"
    a->u : JSON Account data
else Account not found
    a->u : 404 Not Found
    a->u : "Account not found"
end

@enduml