@startuml
'https://plantuml.com/sequence-diagram

title GET /prior/api/v1/character

actor User as u
entity API as a
database Database as d

u->a : GET /prior/api/v1/character
a->d: Find all characters
d-->a : Character data
a->a : Validate characters

alt Character found
    a->u : 200 OK
    a->u : "Data retrieved successfully"
    a->u : JSON Character data
else Character not found
    a->u : 404 Not Found
    a->u : "Character not found"
end

@enduml