@startuml
'https://plantuml.com/sequence-diagram

title GET /prior/api/v1/market

actor User as u
entity API as a
database Database as d

u->a : GET /prior/api/v1/market
a->d: Find all markets
a->a : Validate markets

alt Market found
    d-->a : Market data
    a->u : 200 OK
    a->u : "Data retrieved successfully"
    a->u : JSON Market data
else Market not found
    a->u : 404 Not Found
    a->u : "Market not found"
end

@enduml