@startuml
'https://plantuml.com/sequence-diagram

title GET /prior/api/v1/character/{id}

actor User as u
entity API as a
database Database as d

u->a : GET /prior/api/v1/character/{id}
a->d: Find character by id
a->a : Validate character

alt Character found
    d-->a : Character data
    a->u : 200 OK
    a->u : "Data retrieved successfully"
    a->u : JSON Character data
else Character not found
    a->u : 404 Not Found
    a->u : "Character not found"
end

@enduml