@startuml
'https://plantuml.com/sequence-diagram

title GET /prior/api/v1/inventory/{id}

actor User as u
entity API as a
database Database as d

u->a : GET /prior/api/v1/inventory/{id}
a->d: Find inventory by id
d-->a : Inventory data
a->a : Validate inventory

alt Inventory found
    a->u : 200 OK
    a->u : "Data retrieved successfully"
    a->u : JSON Inventory data
else Inventory not found
    a->u : 404 Not Found
    a->u : "Inventory not found"
end

@enduml