@startuml
'https://plantuml.com/sequence-diagram

title GET /prior/api/v1/monster

actor User as u
entity API as a
database Database as d

u->a : GET /prior/api/v1/monster
a->d: Find all monsters
d-->a : Monster data
a->a : Validate monsters

alt Monster found
    a->u : 200 OK
    a->u : "Data retrieved successfully"
    a->u : JSON Monster data
else Monster not found
    a->u : 404 Not Found
    a->u : "Monster not found"
end

@enduml