@startuml
'https://plantuml.com/sequence-diagram

title GET /prior/api/v1/inbox

actor User as u
entity API as a
database Database as d

u->a : GET /prior/api/v1/inbox
a->d: Find all inboxes
d-->a : Inbox data
a->a : Validate inboxes

alt Inbox found
    a->u : 200 OK
    a->u : "Data retrieved successfully"
    a->u : JSON Inbox data
else Inbox not found
    a->u : 404 Not Found
    a->u : "Inbox not found"
end

@enduml